### ISSUE TITLE
"advance" not available in Swift 2.0

### ISSUE THREAD

**Issue by rexstjohn** [manavgabhawala/UberSDK#1]
If you build the iOS SDK using Swift 2.0 you will get an error from UberUserAuthenticator.swift to the effect that the "advance" function is no longer available. Solution is to use advancedBy instead as below.

let startIndex = scopesString.startIndex.advancedBy(3)
scopesString = scopesString.substringFromIndex(startIndex)

See: http://stackoverflow.com/questions/32237243/advancedby-api-in-swift-2-0

**Comment by manavgabhawala** [comment]
Has been fixed on the dev branch. It will be updated on the master in the next update.
